version: '3.6'
services:
  db:
    image: kelpdigital/postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
